module directx.d2d1_3;
//---------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All rights reserved.
//
// This file is automatically generated.  Please do not edit it directly.
//
// File name: D2D1_3.h
//---------------------------------------------------------------------------

version(Windows):

public import directx.d2d1_2;
public import directx.d2d1effects_2;

// TODO:
