module directx.d2d1effectauthor_1;
//---------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All rights reserved.
//
// This file is automatically generated.  Please do not edit it directly.
//
// File name: D2D1EffectAuthor_1.h
//---------------------------------------------------------------------------

version(Windows):

public import directx.d2d1_3;
public import directx.d2d1effectauthor;

// TODO:
