module directx.d2d1_2;
//---------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All rights reserved.
//
// This file is automatically generated.  Please do not edit it directly.
//
// File name: D2D1_2.h
//---------------------------------------------------------------------------

version(Windows):

public import directx.d2d1_1;
public import directx.d2d1effects_1;

// TODO:
