module directx.d2d1_3;
//---------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All rights reserved.
//
// This file is automatically generated.  Please do not edit it directly.
//
// File name: D2D1_3.h
//---------------------------------------------------------------------------

version(Windows):


version(Direct2D_1_3)
    version = Direct2D_1_2;
version(Direct2D_1_2)
    version = Direct2D_1_1;
version(Direct2D_1_1):
    version = Direct2D_1_0;

version(DirectWrite):
version(WinCodec):
version(Direct2D_1_3):

public import directx.d2d1_2;
public import directx.d2d1effects_2;

// TODO:
